Added move sound for hovercraft. Fixes playing sound for other types …
OpenE2140/OpenE2140 pull request #127
Opened 2023-04-07 19:16 UTC by michal-mad

…of units f.e flying, floating, hovering etc

Closes #126

2023-04-07 19:40 UTC, IceReaper commented
LGTM

2023-04-07 20:44 UTC, Dzierzan commented
Sounds like in vanilla.

2023-04-08 11:04 UTC, michaeldgg2 requested changes

2023-04-08 11:04 UTC, michaeldgg2 commented on mods/e2140/content/ucs/sounds/31.wav
Please don't use just number for the sound file. Just because sound files in assets don't have filenames, it doesn't mean we should give them any.

So probably something like `wtp_100_engine.wav`?

2023-04-08 11:06 UTC, IceReaper commented on mods/e2140/content/ucs/sounds/31.wav
It's for all hover units and mid-air-hover-planes. I would generalize that

2023-04-08 18:51 UTC, michal-mad commented on mods/e2140/content/ucs/sounds/31.wav
This sound is used for 2 units in vanilla game: WTP 100 and Heavy Lifter (AFAIK). Given the fact that Heavy Lifter moves *all the time* we initially discussed that it doesn't make sense to use it for move sound - it will be very annoying in a long run. Effectively this sound would be used by WTP 100 exclusively.

Thus I would stick to @michaeldgg2 proposal: `wtp_100_enigne.wav`. What do you think?

2023-04-08 18:52 UTC, IceReaper commented on mods/e2140/content/ucs/sounds/31.wav
The big bomber (and other aircrafts) has another sound?

2023-04-08 19:15 UTC, michal-mad commented on mods/e2140/content/ucs/sounds/31.wav
@IceReaper You're right. The big bomber (Hellwind) does make that sound too. Gargoyle I - doesn't make any sound, Gargoyle II - has its own unique one. ED aircrafts have different sound(s) - propeller blades or none.

Getting back to the name. How about `anti_gravity_engine.wav`? Fits both to me.

2023-04-08 21:40 UTC, IceReaper commented on mods/e2140/content/ucs/sounds/31.wav
I would prefer that, yes

2023-04-09 14:39 UTC, michal-mad commented on mods/e2140/content/ucs/sounds/31.wav
done

2023-04-09 20:29 UTC, michaeldgg2 commented on mods/e2140/content/ucs/sounds/31.wav
But if we use it for Heavy Lifter too, then it should go into `content/shared/sounds/`, right? Heavy Lifter is available for both factions.

2023-04-09 22:49 UTC, michal-mad commented on mods/e2140/content/ucs/sounds/31.wav
@michaeldgg2 despite the vanilla, we would like not to use it for Heavy Lifter because.. as stated above:

`Given the fact that Heavy Lifter moves all the time we initially discussed that it doesn't make sense to use it for move sound - it will be very annoying in a long run`

It's kind of improvement over vanilla state. What do you think?

2023-04-17 20:03 UTC, closed without merging