Implemented infantry units and barracks.
OpenE2140/OpenE2140 pull request #181
Opened 2023-05-02 23:20 UTC by Dzierzan

- OpenRA doesn't support random death animations for specific damage type. Issue #xx.
- I made duplicate death for UCS and Civils, so they do not disappear when they are killed by unknown damage type (although it should fall back to `die`, but it doesn't).
- Wrong offsets for infantry aiming and shooting, depends on #128.
- Used `TurnOnIdle` trait for infantry. While they do not do that in vanilla, I strongly believe it's a nice addon which makes infantry more alive when idle.
- I didn't try to mimic vanilla idle animation behavior, instead I set short sequence which is triggered from time to time using `WithIdleAnimation`.
- Aiming and shooting sequences were seperated in virtual assets.
- Used IceReaper's `WithAimAttackAnimation` for aiming. Technically ORA's `WithAimAnimation` should work too, but for some odd reason I couldn't force it to work. Testcase in RA mod, for arty worked correctly.
- `WithAimAttackAnimation` needs to be conditonal or support armaments (primary, secondary...) for A01 grenade throw.
- Infantry bodies do not decay. Issue #xx.
- Implemented custom voices for UCS infantry. Added basically +5% pitch and some reverb effect. I didn't touch "OK" and "Waiting" voices as they are fine.
- Barracks do not have sprites for door animations when they're damaged. So I disabled that animation when a building is damaged. In vanilla, full HP door animation is used for damaged building, it looks just awful.
- `WithProductionDoorOverlay` trait was used for door animation. There's one issue with that. By default it always renders the first frame, the problem is, Earth 2140 doesn't have cut idle sprites for door animations. I patched it by making an extra sprite for both barracks.
  But IMO this solution is not clean and custom trait has to be written. I'd just use `WithProductionDoorOverlay` as base, but do not render the first sprite all the time. Also most likely ZOffset is set quite high for this trait which I cannot overcome with setting own ZOffset. There's apparently value 512
in the trait, if removed, then an infantry actor spawns correctly above building sprite.

2023-05-14 13:46 UTC, IceReaper reviewed
Why do we have custom sounds added? Wont that generate problems with different translations?

2023-05-14 13:46 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Misc/WithAimAttackAnimation.cs
> +	[Desc("Displayed while attacking.")]
copy & paste?

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/content/ed/voices.yaml
> +		Escort: 72.smp, 73.smp
can we move escort before attack? so it makes an ascending order? :)

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/content/ed/buildings/bio_center/rules.yaml
> +		Sequence: opening
Encyclopedia :)

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/content/ucs/buildings/robot_factory/rules.yaml
> +		Sequence: opening
Encyclopedia :)

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/content/ucs/infantry/silver_one/rules.yaml
> +		Order: 3
Order: 1

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/content/ucs/infantry/silver_r/rules.yaml
> +		Order: 3
Order: 2

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/content/ucs/infantry/silver_t/rules.yaml
> +		Order: 3
Order: 4

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/virtualassets/SPRU0.MIX.VirtualAssets.yaml
> +		aim:  721-730[0_1_1] 8
single space :-P

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/virtualassets/SPRU0.MIX.VirtualAssets.yaml
> +		aim:  761-770[0_1_1] 8
single space :-P

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/virtualassets/SPRU0.MIX.VirtualAssets.yaml
> +		aim:  801-810[0_1_1] 8
single space :-P

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/virtualassets/SPRU0.MIX.VirtualAssets.yaml
> +		aim:  881-890[0_1_1] 8
single space :-P

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/virtualassets/SPRU0.MIX.VirtualAssets.yaml
> +		aim:  921-930[0_1_1] 8
single space :-P

2023-05-14 13:46 UTC, IceReaper commented on mods/e2140/virtualassets/SPRU0.MIX.VirtualAssets.yaml
> +		aim:  971-980[0_1_1] 8
single space :-P

2023-05-14 13:53 UTC, Dzierzan commented on OpenRA.Mods.OpenE2140/Traits/Misc/WithAimAttackAnimation.cs
> +	[Desc("Displayed while attacking.")]
Yes, you know I'm no C# coder.

2023-05-14 13:53 UTC, Dzierzan commented on mods/e2140/content/ed/voices.yaml
> +		Escort: 72.smp, 73.smp
Maybe for another PR?

2023-05-14 13:53 UTC, Dzierzan commented on mods/e2140/content/ed/buildings/bio_center/rules.yaml
> +		Sequence: opening
No idea what you mean.

2023-05-14 13:53 UTC, Dzierzan commented on mods/e2140/content/ucs/buildings/robot_factory/rules.yaml
> +		Sequence: opening
No idea what you mean.

2023-05-14 14:08 UTC, Dzierzan commented
You expect supporting translations? Besides if so, it will just fall back to the translated voices. I only added minor improvements, but I didn't create totally new voice (like I did in OpenKrush).

2023-05-15 21:23 UTC, michaeldgg2 requested changes

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/infantry/a02/rules.yaml
> +		Description: The A02 is an enhanced version of the A01. They have the same features and differ only in weaponry. The A02 has a rocket launcher and is ideal for destroying heavyweight enemy vehicles
Nitpick:

```suggestion
		Description: The A02 is an enhanced version of the A01. They have the same features and differ only in weaponry. The A02 has a rocket launcher and is ideal for destroying heavyweight enemy vehicles. You can also use it for ground to air combat, its wide range rocket launcher enabling you to hit airborne targets.
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/voices.yaml
> +		Escort: 72.smp, 73.smp
Guard voice line (`72.smp`) is played in Earth 2140 when *Guard* command is issued. This is different than Guard in OpenRA. This Guard command (in Earth 2140) is somewhat similar to a mix between Attack Anything and Defend unit stances: unit defends the spot, where the command was activated and chases enemies but only to certain distance. A bit off topic, but still it's good to clarify things.

Generally it's better if PR is as small as possible and this change is not related to infantry.

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ucs/buildings/robot_factory/rules.yaml
> +		Name: Light Robot Factory
It's called only *Robot Factory*. Yes, the robots it produces are definitely lighter than those produced by Heavy Tech, but let's not change stuff just for the sake of it. For me as fan and player of Earth 2140 it suggests it's some sort of new/different building.

```suggestion
		Name: Robot Factory
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ucs/buildings/robot_factory/rules.yaml
> +		Title: UCS Light Robot Factory
Same as above, it's just *Robot Factory*.

```suggestion
		Title: UCS Robot Factory
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ucs/buildings/robot_factory/rules.yaml
> +		Name: Mobile Light Robot Factory
```suggestion
		Name: Mobile Robot Factory
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/core/rules/defaults.yaml
> +	# Infatry has an animation while moving.
```suggestion
	# Infantry has an animation while moving.
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/shared/buildings/air_base/rules.yaml
> +		LocalCenterOffset: 0,0,-256
Why is this necessary? Does original game have the building's sprite shifted like this?

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ucs/buildings/robot_factory/rules.yaml
> +	ProductionQueue:
Use `^CoreFactory` that defines this basic stuff for production buildings. It also adds `RallyPoint` trait.

Yes there's separate `^CoreElevatorFactory` which is used for factories with elevators only of course.

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/buildings/bio_center/rules.yaml
> +		Name: Bionic Production Center
Similar to Robot Factory, please use original name: *Bio-Center* (with or without hyphen).

```suggestion
		Name: Bio-Center
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/buildings/bio_center/rules.yaml
> +	ProductionQueue:
Use `^CoreFactory` similar to Robot Factory

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/buildings/bio_center/rules.yaml
> +		Title: Bionic Production Center (Bio Center)
```suggestion
		Title: Bio-Center
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/infantry/a01/weapons.yaml
> +ed_infantry_a01_machine_gun_vs_infantry:
Why is this separate weapon necessary? Android A01 shoots infantry with machine gun. Also whether machine gun or grenades are used when shooting at ground, it actually depends on what was previous target: if it was infantry, then machine gun is used, if vehicle/structure/etc. then grenades (not sure about trees and other terrain objects though).

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/infantry/a01/rules.yaml
> +		Name: A01 Android
Use original name *Android A01*:

```suggestion
		Name: Android A01
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/infantry/a02/rules.yaml
> +		Name: A02 Android
Use original name *Android A02*:

```suggestion
		Name: Android A02
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/infantry/a03/rules.yaml
> +		Name: A03 Android
Use original name *Android A03*:

```suggestion
		Name: Android A03
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/infantry/a04/rules.yaml
> +		Name: A04 Android
Use original name *Android A04*:

```suggestion
		Name: Android A04
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/infantry/a04/rules.yaml
> +		Title: A04 Android
Use original name *Android A04*:

```suggestion
		Title: Android A04
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/infantry/a03/rules.yaml
> +		Title: A03 Android
Use original name *Android A03*:

```suggestion
		Title: Android A03
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/infantry/a02/rules.yaml
> +		Title: A02 Android
Use original name *Android A02*:

```suggestion
		Title: Android A02
```

2023-05-15 21:23 UTC, michaeldgg2 commented on mods/e2140/content/ed/infantry/a01/rules.yaml
> +		Title: A01 Android
Use original name *Android A01*:

```suggestion
		Title: Android A01
```

2023-05-16 17:53 UTC, Dzierzan commented on mods/e2140/content/ed/infantry/a01/weapons.yaml
> +ed_infantry_a01_machine_gun_vs_infantry:
I miscalculated that. It's fixed.

2023-05-18 15:26 UTC, closed without merging