Added new warhead that can spawn shrapnels
OpenE2140/OpenE2140 pull request #206
Opened 2023-05-14 20:32 UTC by michal-mad

Removed redundant play sound effect

Added debris to all current units.

2023-05-14 20:37 UTC, Dzierzan commented
![debris](https://github.com/OpenE2140/OpenE2140/assets/17529329/a0f592cf-30f8-44dd-bcfb-b1083c736b4a)

2023-05-15 20:42 UTC, michaeldgg2 commented
What are those thick black borders when shrapnel hits the ground?

![image](https://github.com/OpenE2140/OpenE2140/assets/119738087/ad790e79-651f-4ea7-b87d-1195f4954a4c)

2023-05-15 20:50 UTC, Dzierzan commented
Smoke, just like in vanilla. However they're too dark right now. So it has to be improved later.

Some debris have smoke when they hit ground, some don't. Check it out in og game.

2023-05-15 20:51 UTC, Dzierzan commented
![image](https://github.com/OpenE2140/OpenE2140/assets/17529329/8af73ee5-dde1-4dfd-a597-40171649229c)

2023-05-23 19:29 UTC, michaeldgg2 requested changes
Currently I see only code style issues, will need to test later.

2023-05-23 19:29 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +						DamageModifiers = firedBy.TraitsImplementing<IFirepowerModifier>()
Code style: either put it on single line, or indent it properly. Same goes for all LINQ queries.

2023-05-23 19:29 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +		if (Weapons.Length != Delays.Length)
Use `this.` for instance member access everywhere.

2023-05-28 21:57 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +		if (Weapons.Length != Delays.Length)
even for properties? It (kinda) makes sense for fields but it's obvious that properties are member of this class.. seems redundant

2023-05-28 23:25 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +		if (Weapons.Length != Delays.Length)
My vote would also be to "always prefix". It makes clear in my opinion where particular stuff comes from

2023-05-29 20:07 UTC, michaeldgg2 requested changes

2023-05-29 20:07 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +		var actorAtImpact = this.ImpactActors ? ActorTypeAtImpact(world, pos, firedBy) : ImpactActorType.None;
```suggestion
		var actorAtImpact = this.ImpactActors ? this.ActorTypeAtImpact(world, pos, firedBy) : ImpactActorType.None;
```

Still missing `this`

2023-05-29 20:07 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +		return IsValidTarget(dat > AirThreshold ? targetTypeAir : world.Map.GetTerrainInfo(cell).TargetTypes);
`this`

2023-05-29 20:07 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +			if (!AffectsParent && victim == firedBy)
`this`

2023-05-29 20:07 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +			if (IsValidAgainst(victim, firedBy))
`this`

2023-05-29 20:07 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +		if (actorAtImpact == ImpactActorType.None && !IsValidAgainstTerrain(world, pos))
`this`

2023-06-01 16:16 UTC, michaeldgg2 commented
Merged in babf564d3a07f4a2e9b3c6f3ac9c88ad02f91b4b

2023-06-01 16:16 UTC, closed without merging