Added Silo building and nuclear rocket superweapon.
OpenE2140/OpenE2140 pull request #410
Opened 2023-07-19 19:56 UTC by Dzierzan

Things to be done:
- Nuclear rocket needs a thruster tail which has to work as an overlay sprite for the projectile.
- `SupportPowers` wants `chrome` palette for clock. I added dummy palette to avoid the crash.
- `SupportPowers` needs to be able to support faction suffix for clock.
- `NukePower` needs to be able to support faction suffic for icons.

Notes:
- Damage - nuclear rocket can destroy Shelter and it has 2000 HP. So I concluded the least amount of damage it deals is 2000.
- According to the HD version, it takes 4 mins and 20 seconds to reload.
- The weapon spread damage is 4 tiles.
- Added missing damage state sprites.
- Cut off feature which elevators use, needs to be added for silo in the future (pure cosmetic thing).
- The silo starts fully charged as it is in vanilla.
- Multiple silos are allowed (no hard-cap, though)

2023-07-20 17:07 UTC, Dzierzan commented
`WithSupportPowerActivationAnimation` could support playing sound as both silo and plasmablast have sort of opening sound. PlasmaBlast has a delay between playing animation and actually firing.

Right now opening sound was moved to weapon which is IMO bad in the long run.

2023-07-20 18:01 UTC, michaeldgg2 commented
> PlasmaBlast has a delay between playing animation and actually firing.

`NukePower` has `MissileDelay`:
```
[Desc("Delay (in ticks) after launch until the missile is spawned.")]
public readonly int MissileDelay = 0;
```
Can't you use this?

> WithSupportPowerActivationAnimation could support playing sound as both silo and plasmablast have sort of opening sound. 

Support powers in general support `LaunchSound` and `IncomingSound`. `LaunchSound` is played when the support power is yours or one of your allies and `IncomingSound` if it belongs to an enemy.

It is `UI`-type sound, but can it be used?

2023-07-20 18:07 UTC, Dzierzan commented
Yes, I used for the missile, but it's for delaying the actual firing. So right now, opening sound is played when the building fires. Before that happens, you can see the animation without sound. But for the silo, it's quick enough, so you don't really notice it. But for PlasmaBlast, it will be more noticable, as there's bigger delay between starting the animation and firing, hence moving opening sound to `WithSupportPowerActivationAnimation` would be better.

2023-07-20 18:18 UTC, michaeldgg2 commented
`WithSupportPowerActivationAnimation` is executed when the support power is activated. And that happens in the same tick as when `LaunchSound` / `IncomingSound` (and other sounds such as speech notifications) are played. These are `UI`-type sounds, so if that is not enough, we need a new trait. `WithSupportPowerActivationAnimation` is very simple, but also focused when it comes to its function. Adding sound feature to it isn't really a good idea (it likely won't get past PR).

2023-07-22 21:43 UTC, Dzierzan commented
Added PB Cannon and its superweapon.

2023-08-25 13:50 UTC, michaeldgg2 requested changes

2023-08-25 13:50 UTC, michaeldgg2 commented on mods/e2140/content/ed/defenses/silo/weapons.yaml
> +		ValidTargets: Ground, Ship
Superweapons deal damage to aircraft too

2023-08-25 13:50 UTC, michaeldgg2 commented on mods/e2140/content/ucs/defenses/pb_cannon/weapons.yaml
> +		ValidTargets: Ground, Ship
Superweapons deal damage to aircraft too

2023-08-25 22:27 UTC, merged