Adds CreateSmokeEffectWarhead which can produce smoke on weapon's impact
OpenE2140/OpenE2140 pull request #425
Opened 2023-08-06 21:32 UTC by michal-mad

2023-08-07 11:36 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/Effects/FloatingSprite.cs
> + * Copyright (c) The OpenRA Developers and Contributors
The whole file is taken from ORA Common because it's internal in there. We can ask to make it public on their end (I wonder how much time will it take..) or keep it on our side which will be handy anyway because of wind implementation some time in the future.

2023-08-07 17:16 UTC, Dzierzan commented
Tested and works.
![darksmoke](https://github.com/OpenE2140/OpenE2140/assets/17529329/2fd31ab7-dfab-4fc7-a48f-552d93b7d57f)

However, this PR depends on my husks PR as I made some changes to the smoke. So I will hold up doing any changes in this PR.
https://github.com/Dzierzan/OpenE2140/blob/husks/mods/e2140/content/shared/sequences/misc.yaml#L1-L11

2023-08-07 20:06 UTC, Dzierzan approved these changes

2023-08-23 17:06 UTC, michaeldgg2 commented
Shouldn't the `CreateSmokeEffect` be used for HT 33 LR's lasers too?

2023-08-23 17:07 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Effects/FloatingSprite.cs
> + * Copyright (c) The OpenRA Developers and Contributors
Made PR here, it's very simple, so it might not take too much time (like other, more complicated PRs):

https://github.com/OpenRA/OpenRA/pull/21017

2023-08-23 18:20 UTC, Dzierzan commented
Yes, but this PR is meant to laid foundation and to see if you even accept it. Why work on the rest of actors if you can say no? If you say yes, I will update yaml rules for the rest of actors which need that.

2023-08-23 20:27 UTC, michaeldgg2 requested changes

2023-08-23 20:27 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/EffectWarhead.cs
> +	/// <param name="victim"></param>
Add comments or remove empty elements.

2023-08-23 20:27 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/EffectWarhead.cs
> +
Remove empty line.

2023-08-23 20:27 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/EffectWarhead.cs
> +	/// <returns></returns>
Add comment or remove empty element.

2023-08-23 20:27 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/EffectWarhead.cs
> +	/// <param name="target"></param>
Add comments or remove empty elements.

2023-08-28 21:13 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/Effects/FloatingSprite.cs
> + * Copyright (c) The OpenRA Developers and Contributors
They've merged your PR. Can we update an engine?

2023-08-29 15:17 UTC, michaeldgg2 commented
Implemented in 6805ff045da57c805c8d4313766b33a80b52b48f and 23d5bd69f5b3d00bbe0c07d618469e4c5a57265f

2023-08-29 15:17 UTC, closed without merging

2023-09-02 15:31 UTC, GraionDilach commented on OpenRA.Mods.OpenE2140/Effects/FloatingSprite.cs
> + * Copyright (c) The OpenRA Developers and Contributors
Late response but upstream should be interested in a potential wind expansion of this logic. The core of the code was originally written for TS particles which were affected by a wind effect, but a TS/RA2 bug ensured that the wind in those games was always skewered towards the right edge of the screen.