Improved Mech movement
OpenE2140/OpenE2140 pull request #45
Opened 2023-02-23 23:40 UTC by michal-mad

This is regarding: [#30 ](https://github.com/michaeldgg2/OpenE2140/issues/30)

This PR introduces upper body movement for mech while walking. It should also better sync with moving sound and legs motion relative to travelled distance. Little more tweaks on the matter may be made according to comments.

Orig behavior:
![anim-orig](https://user-images.githubusercontent.com/24232344/221055967-1f4c6d0c-9e27-469a-91cb-ac7c23e61204.gif)

Proposed behavior:
![Animation2](https://user-images.githubusercontent.com/24232344/221055865-8145797b-a2ad-43ee-9072-fca3cb0fbda0.gif)

2023-02-23 23:46 UTC, michal-mad commented
1. Currently only Tiger Assault is modified. I left others unthouched in case you'd want to see in game how they differ
2. I am sorry about changes in yaml as I know they're pretty bad because ^CoreTurret is a base for building (watchtower) and unit..  couldn't figure out what would be the best approach here.. Any suggestions?

2023-02-24 13:12 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/MechMovement.cs
> +public class MechMovement : WithSpriteTurret
The new names does hide the fact for prople who know openra, that this is WithSpriteTurret. I would rename this to WithMovingSpriteTurret

2023-02-24 13:12 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/MechMovement.cs
> +		mobile = self.Trait<Mobile>();
.Trait and .First may lead into crashes when other yaml wired traits are defined in a different order. To be order-independent, we should move these to INotifyCreated.
Also to let the linter hind about missing requirements, the TraitInfo may need some Requires<>, or we should change this to make it optional, so we wont cause a crash, but simply dont work as desired when something is missing.

2023-02-24 13:26 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/Traits/Rendering/MechMovement.cs
> +public class MechMovement : WithSpriteTurret
Got it. I agree.

2023-02-24 13:30 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/Traits/Rendering/MechMovement.cs
> +		mobile = self.Trait<Mobile>();
If you look into base you'll find out that it basically repeats traits retrieval logic. Ideally, the base class would expose protected fields so we would be able to use it (but that of course requires changes in OpenRA).

Given the fact that base class does it in exactly same manner do you still insist on your proposal or rather ask for such fields to have 'protected' access modifier?

2023-02-24 15:00 UTC, michaeldgg2 commented
After changes suggested in the comments the PR will be approved.

2023-02-24 15:01 UTC, michaeldgg2 requested changes

2023-02-24 15:01 UTC, michaeldgg2 commented on mods/e2140/content/core/rules/defaults.yaml
> +	MechMovement:
Move this to `mods/e2140/content/ucs/rules.yaml` under `^UcsTurretedMech` (like we discussed), replace `WithSpriteTurret` with this (i.e. use notation `-WithSpriteTurret`).

2023-02-24 15:01 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Traits/Rendering/MechMovement.cs
> +		mobile = self.Trait<Mobile>();
I'd say exposing fields that only retrieve necessary traits from actor as protected, so it's not duplicated, is not really good enough reason to do this.

As for requirements, I agree with using `Requires<T>`, this makes it obvious that the dependencies are. Also I don't this trait being used anywhere else besides UCS mechs (i.e. `^UcsMech`).

2023-02-24 15:01 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Traits/Rendering/MechMovement.cs
> +public class MechMovement : WithSpriteTurret
I agree with `WithMovingSpriteTurret` too.

2023-02-24 22:39 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/Traits/Rendering/MechMovement.cs
> +		mobile = self.Trait<Mobile>();
Done

2023-02-24 22:40 UTC, michal-mad commented on mods/e2140/content/core/rules/defaults.yaml
> +	MechMovement:
Done

2023-02-25 11:09 UTC, IceReaper reviewed
Overall a good and awesome PR :) While my proposed changes look like much, its actualy not much, but the impact of those few things spreads through much of the file, sorry for that :/
Anyway, this is again just a suggestion. @michaeldgg2 has to decide ;)

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/OpenRA.Mods.OpenE2140.csproj
> +
```suggestion
```

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	private Turreted turreted;
```suggestion
	private Mobile? mobile;
	private BodyOrientation? body;
	private Turreted? turreted;
```

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +		turreted = self.TraitsImplementing<Turreted>().First(tt => tt.Name == info.Turret);
```suggestion
		this.mobile = self.TraitOrDefault<Mobile>();
		this.body = self.TraitOrDefault<BodyOrientation>();
		this.turreted = self.TraitsImplementing<Turreted>().First(turreted => turreted.Name == this.info.Turret);
```

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/OpenRA.Mods.OpenE2140.csproj
> +
Whether we should drop nullability (im against it personaly, but im not the project owner), should be a seperate discussion.

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	private Turreted turreted;
To go conform with current nullability usage.

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +public class WithMovingSpriteTurretInfo : WithSpriteTurretInfo, Requires<TurretedInfo>, Requires<BodyOrientationInfo>, Requires<MobileInfo>
```suggestion
public class WithMovingSpriteTurretInfo : WithSpriteTurretInfo, Requires<MobileInfo>
```

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +public class WithMovingSpriteTurretInfo : WithSpriteTurretInfo, Requires<TurretedInfo>, Requires<BodyOrientationInfo>, Requires<MobileInfo>
Sorry, my bad. Parent class already required those two.

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	public override object Create(ActorInitializer init) { return new WithMovingSpriteTurret(init.Self, this); }
```suggestion
	public readonly int OffsetHigh = 40;
	public readonly int OffsetLow = -30;
	public readonly int Frequency = 20;
	public readonly int Duration = 1000;

	public override object Create(ActorInitializer init) { return new WithMovingSpriteTurret(init.Self, this); }
```

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	public override object Create(ActorInitializer init) { return new WithMovingSpriteTurret(init.Self, this); }
OpenRA does not use floats but relies on ints. Especialy as you convert the results to back ints anyway before usage.
Also i would move them to the Info class, so particular other actors may be able override these. Same for the frequence and duration, so the actual values are yaml overridable. Makes it not hardcoded to this specific sequence tickrate of 70.

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +		turreted = self.TraitsImplementing<Turreted>().First(tt => tt.Name == info.Turret);
See above. We use this. prefixes in out codebase. Also i would swap Trait to TraitOrDefault, as the fields will be marked as nullable anyway. This might resolve a theoreticall NRE case, and as said before, when using nullable anyway it doesnt hurt :)

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +[Desc("Renders walking unit with a turret as its upper body move up and down imposed by legs motion.")]
```suggestion
[Desc("Renders walking unit with a turret as its upper body move up and down imposed by legs motion.")]
[UsedImplicitly(ImplicitUseTargetFlags.WithMembers)]
```

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +[Desc("Renders walking unit with a turret as its upper body move up and down imposed by legs motion.")]
Just for user who use JetBrains Rider (like me), so rider wont warn about the fields not being set and suggesting a convert to const.

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	private readonly float offsetLow = -30f;
```suggestion
```

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	private readonly float offsetLow = -30f;
See above.

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	private float frequency = 0.02f;
```suggestion
	private int current;
	private int frequency;
```

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	private float frequency = 0.02f;
See above

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +		return offset;
```suggestion
		if (this.mobile == null)
			return offset;

		if (this.mobile.CurrentMovementTypes is MovementType.None and not MovementType.Turn)
		{
			this.current = 0;
			this.frequency = this.info.Frequency;

			return offset;
		}

		var interpolation = int2.Lerp(this.info.OffsetLow, this.info.OffsetHigh, this.current, this.info.Duration);

		this.frequency *= this.current > this.info.Duration || this.current < 0 ? -1 : 1;
		this.current += this.frequency;

		var turretMovement = new WVec(WDist.Zero, WDist.Zero, new WDist(interpolation));

		if (this.turreted != null)
			turretMovement = turretMovement.Rotate(this.turreted.WorldOrientation);

		if (this.body != null)
			turretMovement = this.body.LocalToWorld(turretMovement);

		return offset + turretMovement;
```

2023-02-25 11:09 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +		return offset;
Mostly explained above:
- using ints instead of floats to conform openras guidelines of not using floats in the simulation.
- implementing nullability checks
- avoid nesting where possible.

2023-02-25 12:23 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	private Turreted turreted;
This comes back to the discussion on Discord: why making `BodyOrientation` and `Turreted` nullable, when the `WithSpriteTurret` trait already depends on actor having these two traits? We can be sure that the engine (ORA) will not allow creating `WithMovingSpriteTurret` without those two traits. This is the root cause of this issue: delayed initialization of required fields.

Also making `Mobile` trait optional does not make sense: the purpose of this trait is to make turret *on walking mech* move. It does not make sense to me to put this trait on immobile defense tower at all. I agree that traits in general should be reusable in many scenarios, but IMHO this is kind of scenario (immobile actors) is totally outside of `WithMovingSpriteTurret` scope.

2023-02-25 12:25 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/OpenRA.Mods.OpenE2140.csproj
> +
I don't have much experience using nullable reference types in code, but I can see their benefits, so I'd like to keep them. However disabling these warnings makes this feature rather crippled, so it does not really make sense disabling them.

2023-02-25 12:27 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +[Desc("Renders walking unit with a turret as its upper body move up and down imposed by legs motion.")]
That's all right, but VS users like me (without ReSharper) don't know which attributes to add and where, so I don't see adhering to these Rider's (or ReSharper) recommendations as realistic (in this project).

2023-02-25 12:28 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	private Turreted turreted;
I agree. My only main concern here is it violates the nullability rules, and we didn't define yet whether null! Is allowed for this cases. If we decide that, I'll be up for it. My preference is never use ! To ignore nullables, but if you want we define this to be allowed for traits

2023-02-25 12:43 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +[Desc("Renders walking unit with a turret as its upper body move up and down imposed by legs motion.")]
Yeah, not important, I can add them later. But simply copying this in would void me adding it later :D

2023-03-01 09:44 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/OpenRA.Mods.OpenE2140.csproj
> +
Just for the record - this is not about ignoring _all_ nullability checks. This one suppresses exactly one that is reffering in particular to ctor forcing everything to be initialized there. That raises concerns not only in our project but ovearall in the community. There is already GitHub issue for that: https://github.com/dotnet/roslyn/issues/32358

By suppressing it we will avoid boilerplate code and fake indication that some field/properties may be null whereas in fact they are not allowed to be null.

2023-03-01 09:47 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	private Turreted turreted;
I think it should be something more than just satisfy static analyzer or ignore nullables. It indicates to the reader if something in fact is allowed to be null or not. If by design something must be non null then to my taste it is perfectly fine to be followed by !. Also as I mentioned previously, marking all mandatory fields as nullable may be misleading because in fact they are not something optional.

2023-03-01 10:05 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +		turreted = self.TraitsImplementing<Turreted>().First(tt => tt.Name == info.Turret);
Well, the whole feature that is implemented in the class is pointless without `body` or `mobile`. Why then are we going to allow for default for them? Defensive approach? Isn't better to fail fast in case it is used for things that it shouldnt..?

2023-03-01 10:06 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +[Desc("Renders walking unit with a turret as its upper body move up and down imposed by legs motion.")]
I didn't know what it does as well but sure I'll add it as it doesn't hurt as and can help you. Not a problemo

2023-03-01 10:13 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +[Desc("Renders walking unit with a turret as its upper body move up and down imposed by legs motion.")]
Resharper for vs as well as rider itself tell you about performance optimizations and dead code. It can't analyze reflection usage properly. So it tells you you can make the properties const  along the class never instantiated at all. These annotations tell the ide that it will be used implicitly.

2023-03-01 10:19 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +		turreted = self.TraitsImplementing<Turreted>().First(tt => tt.Name == info.Turret);
Hm.. makes sense. I try to avoid exceptions where possible for the sake of modability. If someone removes a trait it won't cause crashes due to dependencies in other traits. But that's just my personal preference. When we have a decision for the nullable thing ill re-review this and revert this suggestion. Was purely to conform the full nullable approach

2023-03-01 21:17 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +	private int current = 0;
0 is the default of int. No need to explicitely set it

2023-03-01 21:17 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +		var isMoving = this.mobile.CurrentMovementTypes is MovementType.None and not MovementType.Turn;
Is none and not turn? Just reviewing from my phone, but shouldn't that be is not none and not turn?

2023-03-01 21:17 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Traits/Rendering/WithMovingSpriteTurret.cs
> +		if (isMoving)
Is this flipped? If it's not moving, apply offset below?

2023-03-03 12:31 UTC, closed without merging