Added support for Inaccuracies for SpawnWeaponsWarhead
OpenE2140/OpenE2140 pull request #469
Opened 2023-09-09 14:31 UTC by michal-mad

Closes #452

2023-09-09 18:16 UTC, Dzierzan commented
It's bugged, debris is not always spawned. In the GIF below I edited `Delays` and commented out `Inaccuracies`.

![debris2](https://github.com/OpenE2140/OpenE2140/assets/17529329/da45475a-7c12-4af1-a808-53672f11f139)

2023-09-09 21:52 UTC, Dzierzan commented
Changes commited and squished. This should be ready for review @michaeldgg2 

There's however this issue where explosions do not follow the husk. I strongly believe this issue should be addressed in another PR.
![wtp](https://github.com/OpenE2140/OpenE2140/assets/17529329/73bcc700-1de4-43d9-be07-ba3e8cf298ca)

2023-09-12 21:08 UTC, michaeldgg2 commented
Please rebase

2023-09-12 21:11 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +using OpenRA.Effects;
Can we please keep all usings above the namespace? :)

2023-09-12 21:11 UTC, IceReaper commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +	public readonly int[] Pieces = { 1, 1 };
Either the comment is wrong, or it should be a single value here: 1

2023-09-12 22:25 UTC, michal-mad commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +	public readonly int[] Pieces = { 1, 1 };
I want for the default to be just 1 piece produced. Range is set from 1 to 1 - technically it's all good. Doing it this way makes the code cleaner (no checks for array boundary, single or double value etc).

It's OK it should stay this way.

2023-09-13 06:30 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +	public readonly int[] Pieces = { 1, 1 };
There's `Util.RandomInRange` that you can use for this, which does all of this for you:

```
public static int RandomInRange(MersenneTwister random, int[] range)
{
	if (range.Length == 0)
		return 0;

	if (range.Length == 1)
		return range[0];

	return random.Next(range[0], range[1]);
}
```

2023-09-13 16:48 UTC, michal-mad commented
Done

2023-09-13 19:25 UTC, michaeldgg2 requested changes

2023-09-13 19:25 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +					Inacurracy = inaccuracy,
`Inaccuracy` in this anonymous object is not used (inaccuracy is calculated into `pos` variable above.

2023-09-13 19:25 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +				var posCapture = pos;
Each piece's position needs to be random. Calculate it here and keep `pos` variable just for actor's center position.

2023-09-13 20:16 UTC, michaeldgg2 requested changes

2023-09-13 20:16 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +			var weaponImpactPosition = new WPos(target.CenterPosition.X, target.CenterPosition.Y, Math.Max(0, target.CenterPosition.Z));
```suggestion
			var weaponImpactPosition = targetCenterPosition + WVec.FromPDF(world.SharedRandom, 2) * inaccuracy.Length / 1024;
```

2023-09-13 20:16 UTC, michaeldgg2 commented on OpenRA.Mods.OpenE2140/Warheads/SpawnWeaponsWarhead.cs
> +		// var pos = new WPos(target.CenterPosition.X, target.CenterPosition.Y, Math.Max(0, target.CenterPosition.Z));
```suggestion
		var targetCenterPosition = new WPos(target.CenterPosition.X, target.CenterPosition.Y, Math.Max(0, target.CenterPosition.Z));
```

2023-09-15 12:32 UTC, michaeldgg2 commented
Implemented in 44299bad58688ef8010270804e488e8ba750e236

2023-09-15 12:32 UTC, closed without merging